name: OWASP ZAP integration
on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Basline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://testphp.vulnweb.com/'

          
